executor: LocalExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.9.1
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow123
    database: airflow

redis:
  enabled: true

webserver:
  service:
    type: LoadBalancer
  defaultUser:
    enabled: true
    username: admin
    password: admin123
    role: Admin
    email: admin@example.com

scheduler:
  replicas: 1

dags:
  persistence:
    enabled: false

logs:
  persistence:
    enabled: false

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"